name: Build Quake
description: "Builds Quake using CMake or pip. Defaults to CMake build."
inputs:
  build_method:
    description: "Build method: 'cmake' or 'pip'"
    required: false
    default: "cmake"
  build_type:
    description: "CMake build type (Release or Debug)"
    required: false
    default: "Release"
  cmake_options:
    description: "Additional options to pass to CMake"
    required: false
    default: ""
  target:
    description: "Build target (e.g., 'quake', 'bindings', or multiple targets separated by spaces)"
    required: false
    default: "quake"
runs:
  using: "composite"
  steps:
    - name: Build Quake using CMake
      if: ${{ inputs.build_method }} == 'cmake'
      shell: bash
      run: |
        echo "Building Quake via CMake..."
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} ${{ inputs.cmake_options }} ..
        make -j$(nproc) ${{ inputs.target }}
    - name: Build Quake using pip
      if: ${{ inputs.build_method }} == 'pip'
      shell: bash
      run: |
        echo "Building Quake via pip..."
        pip install .