# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rwrap.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rwrap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brwrap.proto\"\x10\n\x0e\x43leanupRequest\"\x11\n\x0f\x43leanupResponse\"0\n\x0fInstanceRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07payload\x18\x02 \x02(\x0c\" \n\x10InstanceResponse\x12\x0c\n\x04uuid\x18\x01 \x02(\r\"?\n\x0e\x43ommandRequest\x12\x0c\n\x04uuid\x18\x01 \x02(\x05\x12\x0e\n\x06method\x18\x02 \x02(\t\x12\x0f\n\x07payload\x18\x03 \x02(\x0c\"1\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x02(\x0c\x12\x0e\n\x06\x64irect\x18\x02 \x02(\x08\"?\n\rImportRequest\x12\x0f\n\x07package\x18\x01 \x02(\t\x12\x0f\n\x07\x61s_name\x18\x02 \x01(\t\x12\x0c\n\x04item\x18\x03 \x01(\t\"\x10\n\x0eImportResponse2\xd6\x01\n\x04Wrap\x12\x35\n\x0cSendInstance\x12\x10.InstanceRequest\x1a\x11.InstanceResponse\"\x00\x12\x32\n\x0bSendCommand\x12\x0f.CommandRequest\x1a\x10.CommandResponse\"\x00\x12/\n\nSendImport\x12\x0e.ImportRequest\x1a\x0f.ImportResponse\"\x00\x12\x32\n\x0bSendCleanup\x12\x0f.CleanupRequest\x1a\x10.CleanupResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rwrap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLEANUPREQUEST']._serialized_start=15
  _globals['_CLEANUPREQUEST']._serialized_end=31
  _globals['_CLEANUPRESPONSE']._serialized_start=33
  _globals['_CLEANUPRESPONSE']._serialized_end=50
  _globals['_INSTANCEREQUEST']._serialized_start=52
  _globals['_INSTANCEREQUEST']._serialized_end=100
  _globals['_INSTANCERESPONSE']._serialized_start=102
  _globals['_INSTANCERESPONSE']._serialized_end=134
  _globals['_COMMANDREQUEST']._serialized_start=136
  _globals['_COMMANDREQUEST']._serialized_end=199
  _globals['_COMMANDRESPONSE']._serialized_start=201
  _globals['_COMMANDRESPONSE']._serialized_end=250
  _globals['_IMPORTREQUEST']._serialized_start=252
  _globals['_IMPORTREQUEST']._serialized_end=315
  _globals['_IMPORTRESPONSE']._serialized_start=317
  _globals['_IMPORTRESPONSE']._serialized_end=333
  _globals['_WRAP']._serialized_start=336
  _globals['_WRAP']._serialized_end=550
# @@protoc_insertion_point(module_scope)
