# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quake.distributedwrapper.rwrap_pb2 as rwrap__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in rwrap_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WrapStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendInstance = channel.unary_unary(
            "/Wrap/SendInstance",
            request_serializer=rwrap__pb2.InstanceRequest.SerializeToString,
            response_deserializer=rwrap__pb2.InstanceResponse.FromString,
            _registered_method=True,
        )
        self.SendCommand = channel.unary_unary(
            "/Wrap/SendCommand",
            request_serializer=rwrap__pb2.CommandRequest.SerializeToString,
            response_deserializer=rwrap__pb2.CommandResponse.FromString,
            _registered_method=True,
        )
        self.SendImport = channel.unary_unary(
            "/Wrap/SendImport",
            request_serializer=rwrap__pb2.ImportRequest.SerializeToString,
            response_deserializer=rwrap__pb2.ImportResponse.FromString,
            _registered_method=True,
        )
        self.SendCleanup = channel.unary_unary(
            "/Wrap/SendCleanup",
            request_serializer=rwrap__pb2.CleanupRequest.SerializeToString,
            response_deserializer=rwrap__pb2.CleanupResponse.FromString,
            _registered_method=True,
        )


class WrapServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendImport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WrapServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendInstance": grpc.unary_unary_rpc_method_handler(
            servicer.SendInstance,
            request_deserializer=rwrap__pb2.InstanceRequest.FromString,
            response_serializer=rwrap__pb2.InstanceResponse.SerializeToString,
        ),
        "SendCommand": grpc.unary_unary_rpc_method_handler(
            servicer.SendCommand,
            request_deserializer=rwrap__pb2.CommandRequest.FromString,
            response_serializer=rwrap__pb2.CommandResponse.SerializeToString,
        ),
        "SendImport": grpc.unary_unary_rpc_method_handler(
            servicer.SendImport,
            request_deserializer=rwrap__pb2.ImportRequest.FromString,
            response_serializer=rwrap__pb2.ImportResponse.SerializeToString,
        ),
        "SendCleanup": grpc.unary_unary_rpc_method_handler(
            servicer.SendCleanup,
            request_deserializer=rwrap__pb2.CleanupRequest.FromString,
            response_serializer=rwrap__pb2.CleanupResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("Wrap", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("Wrap", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Wrap(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendInstance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Wrap/SendInstance",
            rwrap__pb2.InstanceRequest.SerializeToString,
            rwrap__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendCommand(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Wrap/SendCommand",
            rwrap__pb2.CommandRequest.SerializeToString,
            rwrap__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendImport(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Wrap/SendImport",
            rwrap__pb2.ImportRequest.SerializeToString,
            rwrap__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendCleanup(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Wrap/SendCleanup",
            rwrap__pb2.CleanupRequest.SerializeToString,
            rwrap__pb2.CleanupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
