name: Setup Environment
description: "Checks out code and sets up the common conda environment."
inputs:
  extra-commands:
    description: "Optional extra shell commands to run after setup"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Setup Conda Environment
      shell: bash
      run: |
        git config --global --add safe.directory '*'
        eval "$(conda shell.bash hook)"
        conda activate quake-env
    - name: Run Extra Commands
      if: ${{ inputs.extra-commands != '' }}
      shell: bash
      run: ${{ inputs.extra-commands }}