name: quake-env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - cpuonly
  - faiss-cpu
  - matplotlib
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid

