name: Container Setup

on:
  workflow_call:

jobs:
  determine-and-build:
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.set_image.outputs.container_image }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for dependency changes
        id: diff
        shell: bash
        run: |
          echo "Checking for dependency changes..."
          if git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" | grep -E 'Dockerfile|conda.yaml'; then
            echo "build_required=true" >> "$GITHUB_OUTPUT"
          else
            echo "build_required=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build Test Container if Needed
        id: build
        if: steps.diff.outputs.build_required == 'true'
        shell: bash
        run: |
          tag="ghcr.io/marius-team/quake/test_container:${{ github.sha }}"
          echo "Building test container: $tag"
          docker build -f environments/ubuntu-latest/Dockerfile -t "$tag" .
          docker push "$tag"
          echo "container_image=$tag" >> "$GITHUB_OUTPUT"

      - name: Set Container Image Output
        id: set_image
        shell: bash
        run: |
          if [ "${{ steps.diff.outputs.build_required }}" = "true" ]; then
            echo "Using test container built in this run."
            image=$(echo "${{ steps.build.outputs.container_image }}")
          else
            image="ghcr.io/marius-team/quake/ubuntu-latest:latest"
            echo "No dependency changes. Using main container: $image"
          fi
          echo "container_image=$image" >> "$GITHUB_OUTPUT"