name: Manual Baseline Generation

on:
#  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  generate-baseline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/marius-team/quake/ubuntu-latest:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Project
        run: |
          git config --global --add safe.directory '*'
          eval "$(conda shell.bash hook)"
          conda activate quake-env
          conda install hydra-core
          pip install .

      - name: Generate Workload and Results
        run: |
          cd test/python/regression
          python run_all_workloads.py --overwrite --name baseline

      - name: Upload Baseline Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: baseline-artifacts
          path: |
            data
            workloads
            results