name: PR Regression Test

on:
  pull_request:
    branches: [ main ]

jobs:
  determine-container:
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.determine.outputs.container_image }}
    steps:
      - name: Determine and Build Container
        id: determine
        uses: ./.github/actions/determine-container
        with:
          event-before: ${{ github.event.before }}
          sha: ${{ github.sha }}

  regression-test:
    needs: determine-container
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.determine-container.outputs.container_image }}
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Build Quake for Regression
        uses: ./.github/actions/build-quake
        with:
          build_method: "cmake"
          build_type: "Release"
          cmake_options: "-DQUAKE_USE_NUMA=OFF -DQUAKE_ENABLE_GPU=OFF -DBUILD_TESTS=ON"
          target: "bindings quake_tests"
      - name: Run Regression Tests
        run: |
          # Run your driver script that organizes regression test operations.
          python ../run_all_workloads.py --name "PR-${{ github.event.number }}"