name: PR Regression Test

on:
  pull_request:
    branches: [ main ]

jobs:
  setup-env:
    uses: ./.github/workflows/setup-environment.yaml

  regression-test:
    needs: setup-env
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.setup-env.outputs.container_image }}
    steps:
      - uses: ./.github/workflows/setup_environment.yaml
      - name: Build Quake for Regression
        uses: ./.github/actions/build-quake
        with:
          build_method: "cmake"
          build_type: "Release"
          cmake_options: "-DQUAKE_USE_NUMA=OFF -DQUAKE_ENABLE_GPU=OFF -DBUILD_TESTS=ON"
          target: "bindings quake_tests"
      - name: Run Regression Tests
        run: |
          # Execute test suite (e.g. run driver script)
          python ../run_all_workloads.py --name "PR-${{ github.event.number }}"