name: PR Regression Test

on:
  pull_request:
    branches: [ main ]

jobs:
  setup-container:
    uses: ./.github/workflows/container_setup.yaml

  regression-test:
    needs: setup-container
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.setup-container.outputs.container_image }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build Quake for Regression
        uses: ./.github/actions/build-quake
        with:
          build_method: "cmake"
          build_type: "Release"
          cmake_options: "-DQUAKE_USE_NUMA=OFF -DQUAKE_ENABLE_GPU=OFF -DBUILD_TESTS=ON"
          target: "bindings quake_tests"

      - name: Get baseline artifacts
        uses: actions/download-artifact@v2
        with:
          name: baseline-artifacts
        run: |
          mv workloads tests/python/regression
          mv results tests/python/regression
          mv data tests/python/regression

      - name: Run Regression Tests
        run: |
          cd tests/python/regression
          python run_all_workloads.py --name "PR-${{ github.event.number }}"