name: Setup Environment

on:
  workflow_call:
    inputs:
      extra-commands:
        description: "Optional extra shell commands to run after the environment is set up"
        required: false
        type: string
        default: ""
jobs:
  determine-container:
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.determine.outputs.container_image }}
    steps:
      - name: Checkout Code (for container determination)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Determine and Build Container
        id: determine
        uses: ./.github/actions/determine-container
        with:
          event-before: ${{ github.event.before }}
          sha: ${{ github.sha }}

  setup:
    needs: determine-container
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.determine-container.outputs.container_image }}
    outputs:
      container_image: ${{ needs.determine-container.outputs.container_image }}
    steps:
      - name: Checkout Code (inside container)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Activate Conda Environment
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          eval "$(conda shell.bash hook)"
          conda activate test-env
      - name: Run Extra Commands
        if: ${{ inputs.extra-commands != '' }}
        shell: bash
        run: ${{ inputs.extra-commands }}